version: '2'
services:
  bootstrap:
    image: parity/parity:v1.7.7
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    command: --config /root/.local/share/io.parity.ethereum/config.toml --unsafe-expose --node-key 091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322
    volumes:
      - "./parity-assets/config.toml:/root/.local/share/io.parity.ethereum/config.toml:ro"
      - "./parity-assets/parity-genesis.json:/root/.local/share/io.parity.ethereum/parity-genesis.json:ro"
      - "./parity-assets/reserved-peers.txt:/root/.local/share/io.parity.ethereum/reserved-peers.txt:ro"
      - "./parity-assets/password:/root/.local/share/io.parity.ethereum/password:ro"
      - "./parity-assets/keys:/root/.local/share/io.parity.ethereum/keys:rw"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "8180:8180"

